services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_control
    ports:
      - "2222:2222"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    depends_on:
      - db
    restart: on-failure

  db:
    image: mongo:8.0
    container_name: control_node_db
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
      - ./mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js:ro
    restart: on-failure

volumes:
  mongo_data: